#Calling Database;
use sales;

#Checking for tables the sales Database consists!!
show tables;

#Quereing all tables in the database!!
select * from customers;
select * from date;
select * from markets;
select * from products;
select * from transactions;

#Quereing Distinct Customers!!
select distinct customer_type from customers;

#Quereing Distinct Product_types!!
Select distinct product_type from products;

#Quereing Distinct Markets and zones!!
select distinct markets_name from markets;
select distinct zone from markets;

#checking if the profit_margin column is same as profit in transaction table!!
select market_code,sales_amount,profit_margin_percentage,round(sales_amount*profit_margin_percentage,2) as profit, profit_margin from transactions;

#checking if there are any other currency type then INR in the data!!
select distinct currency from transactions;

#Correcting the sales_amount w.r.t INR!!
update transactions set sales_amount = sales_amount*88.2 where currency = "USD";
select sales_amount from transactions where currency = "USD";

#Correcting the currency type!!
update transactions set currency = "INR" where currency = "USD";
select distinct currency from transactions;

#Checking for Total sales in each year!!
select sum(sales_amount) as sales, year(order_date) as year from transactions group by year order by sales desc;

#Checking for which month experienced most sales and which month experienced least sales!!
select concat(format(sum(sales_amount)/100000,0),"L") as sales, month(order_date) as month_number,monthname(order_date) as month_name,year(order_date) as year_count from transactions 
group by month_name order by sales desc;

#Checking for which market is generating maximum sales!!
select sum(sales_amount) as sales,market_code,m.markets_name from transactions as t join markets as m on t.market_code = m.markets_code 
group by market_code order by sales desc;

#Checking for which product is generating most sales from both product_type!!
select sum(sales_amount) as sales,t.product_code,p.product_type from transactions as t join products as p on t.product_Code=p.product_code 
group by product_code order by sales desc;

#Top 5 customers giving most sales;
select sum(sales_amount) as sales,t.customer_code,c.custmer_Name,c.customer_type from transactions as t join customers as c on t.customer_code = c.customer_code 
group by customer_code order by sales desc limit 5;

#Percent of sales generated by each customer Type!!
select concat((sum(sales_amount)/(select sum(sales_amount) from transactions))*100,"%") as sales, c.customer_type from transactions as t 
join customers as c on t.customer_code=c.customer_code 
group by c.customer_type order by sales desc;

#Top 5 Most Selling Product!!
select product_code,sum(sales_qty) as Sales_Quantity from transactions group by product_code order by Sales_Quantity desc limit 5;